CREATE DATABASE IF NOT EXISTS HilichurlsRevolt;
USE HilichurlsRevolt;

CREATE TABLE Users(
    Id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(10) NOT NULL UNIQUE,
    PasswordHash BINARY(20) NOT NULL,
    IpOnRegister VARBINARY(16) NULL
);

CREATE TABLE Achievements(
    Id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    UserId MEDIUMINT NOT NULL,
    AchvName VARCHAR(20) NOT NULL,
    TimeOfAward DATETIME NOT NULL,
    IpOfAward VARBINARY(16) NULL,
    UNIQUE (UserId, AchvName),
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE Items(
    Id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ItemName VARCHAR(20) NOT NULL,
    UserId MEDIUMINT NOT NULL,
    ItemCount MEDIUMINT NOT NULL DEFAULT 1,
    UNIQUE (UserId, ItemName),
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE Characters(
    Id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CharName VARCHAR(20) NOT NULL,
    UserId MEDIUMINT NOT NULL,
    Lvl TINYINT UNSIGNED NOT NULL DEFAULT 1,
    Hp MEDIUMINT UNSIGNED NOT NULL,
    UNIQUE (UserId, CharName),
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE CharStatus(
    Id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CharId MEDIUMINT NOT NULL,
    StatusName VARCHAR(20) NOT NULL,
    FOREIGN KEY (CharId) REFERENCES Characters(Id)
)
